/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dcf2xml;

import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.w3c.dom.Node;
import progressmonitor.ProgressBar;
import pruebaxml.Info;
import pruebaxml.LeerXml;
import pruebaxml.PruebaXML;
import tablas.Registro;
import tablas.TablaModeloRegistro;
import tablas.TablaRenderizadorItems;




/**
 *
 * @author mynor
 */
public class PrXML extends javax.swing.JDialog {

    /**
     * Creates new form PruebaXML
     */
    

   
    public JFileChooser jfcExaminarEntrada;
    String entradaxml = "";
    String entradaout = "";
    PruebaXML generador = null;
    LeerXml lector = null;
    private TablaModeloRegistro modeloRegistro = new TablaModeloRegistro();
    private TablaRenderizadorItems renderizador = new TablaRenderizadorItems();
    
    public PrXML(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButton5.setEnabled(false);
        generador = new PruebaXML();
        jLabel5.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pathxmljTextField = new javax.swing.JTextField();
        AbreXMLjButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pathoutjTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AbreoutjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtvariable = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registrojTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prueba archivos digitados usando XML");
        setResizable(false);

        jLabel1.setText("Cargue un archivo XML");

        pathxmljTextField.setEnabled(false);

        AbreXMLjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        AbreXMLjButton.setText("Abrir");
        AbreXMLjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbreXMLjButtonActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Check.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pathoutjTextField3.setEnabled(false);

        jLabel3.setText("Cargue un archivo digitado, para poder ser analizado");

        AbreoutjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Folder.png"))); // NOI18N
        AbreoutjButton.setText("Abrir");
        AbreoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbreoutjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese alguna variable ");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/16/Symbol Refresh 3.png"))); // NOI18N
        jButton5.setText("¡Analizar!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        registrojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Valor digitado", "Posicion Columna", "Posición Fila"
            }
        ));
        jScrollPane1.setViewportView(registrojTable);

        jLabel4.setText("Cantidad de casos/cuestionarios encontrados");

        jTextField5.setEnabled(false);

        jLabel5.setText("Ingrese alguna variable ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtvariable, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pathxmljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(AbreXMLjButton))
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pathoutjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AbreoutjButton))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathxmljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbreXMLjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathoutjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbreoutjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtvariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbreXMLjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbreXMLjButtonActionPerformed
        // TODO add your handling code here:
        //Create a file chooser
        Component cmd = null; ///<---- aqui guarda el contenido del archivo
        JFileChooser jf = new JFileChooser();
        String fileName = "";
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML", "xml");
        jf.setFileFilter(filter);

        try {
            int code = jf.showOpenDialog(cmd);
            if (code == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jf.getSelectedFile();
                fileName = selectedFile.getName();
                
                boolean xml = true;
//                if(selectedFile.length() < 100000)
//                    xml = generador.lectorXML(selectedFile.getAbsolutePath());
                
                if(!xml){
                    new Mensajes().error("XML mal formado.", "Error");
                }else{
                    String charset = "utf-8";
                    progressmonitor.ProgressBar demo = new ProgressBar(selectedFile.getAbsolutePath(), this, charset);
                            demo.setLocationRelativeTo(null);
//                    entradaxml = generador.convertir(selectedFile.getAbsolutePath(), "");
                    pathxmljTextField.setText(jf.getCurrentDirectory().toString() + "\\" + selectedFile.getName());
                    if(!pathoutjTextField3.getText().equals("")){jButton5.setEnabled(true);}
                }
            }

        } catch (Exception f) {
        }


    }//GEN-LAST:event_AbreXMLjButtonActionPerformed

    private void AbreoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbreoutjButtonActionPerformed
        // TODO add your handling code here:
        
     Component cmd = null; ///<---- aqui guarda el contenido del archivo
        JFileChooser jf = new JFileChooser();
        String fileName = "";
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("OUT", "out");
//        jf.setFileFilter(filter);

        try {
            int code = jf.showOpenDialog(cmd);
            if (code == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jf.getSelectedFile();
                fileName = selectedFile.getName();
                entradaout = generador.convertir(selectedFile.getAbsolutePath(), "");
                pathoutjTextField3.setText(jf.getCurrentDirectory().toString() + "\\" + selectedFile.getName());
                if(!pathxmljTextField.getText().equals("")){jButton5.setEnabled(true);}
            }

        } catch (Exception f) {
        }

    }//GEN-LAST:event_AbreoutjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Analizar.
        String var = txtvariable.getText();
        if(var.equals("")){new Mensajes().error("¡Ingrese el nombre del 'Item' que desea buscar!", "Error");
            //¡Prueba de Leer Informacion!
            Info info = new Info(entradaxml, entradaout);
            info.getIn();
        }else{
            try{
                lector = new LeerXml(entradaxml);
                Node aux = lector.getNodeByNameAndRecords(var, lector.getRaiz());
               
                if(aux == null){
                    new Mensajes().error("¡El XML no contiene la variable indicada!", "Error");
                }else if(!aux.getNodeName().equals("ITEM")){
                    new Mensajes().error("¡la variable indicada no es un 'Item' valido!", "Error");
                }else{
                    modeloRegistro = new TablaModeloRegistro();
                    int Nreg = 0;
                    ArrayList<String> regs = new ArrayList<String>();
                    String reg = "";
                    int start = Integer.valueOf(lector.getStart(aux));
                    int len = Integer.valueOf(lector.getLen(aux));
                    Node record = aux.getParentNode();
                    jLabel5.setText(lector.getAtt(aux, "Label"));
                    String[] lineas = entradaout.split("\n");
                    String tipo = "";
                    String att = lector.getAtt(record, "RecordTypeValue");
                    String salida = "";
                    try{

                        for(int x = 0; x < lineas.length; x++){
                            tipo = String.valueOf(lineas[x].charAt(0));
                            if(tipo.equals(att)){
                                salida = lineas[x].substring(start-1, start-1+len);
                                Nreg += 1;
                                reg = Nreg + "," + salida + "," + (start) + "," + (x+1) ;
                                regs.add(reg);
                             }
                        } 
                    }catch(Exception e){}
                    Iterator ilist = regs.iterator();
                    String[] regaux = null;
                    while(ilist.hasNext()){
                        regaux = ilist.next().toString().split(",");
                        modeloRegistro.agregarRegistro(new Registro(regaux[0],regaux[1],regaux[2],regaux[3]));
                    }
                    registrojTable.setModel(modeloRegistro);
                    registrojTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                    registrojTable.setDefaultRenderer(String.class, renderizador);
                    jTextField5.setText(String.valueOf(Nreg));
                }
            }catch(Exception e){
               new Mensajes().error("¡Error en el archivo XML!", "Error");
            }
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbreXMLjButton;
    private javax.swing.JButton AbreoutjButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField pathoutjTextField3;
    private javax.swing.JTextField pathxmljTextField;
    private javax.swing.JTable registrojTable;
    private javax.swing.JTextField txtvariable;
    // End of variables declaration//GEN-END:variables

    public void setXMl(String entrada) {
        entradaxml = entrada;
    }
}

/*
 * 
 * String salida = lineas[UbicacionRecordVariable-1].substring(start-1, start-1+len);
                    
                    Nreg += 1;
                    reg = Nreg + "," + salida + "," + (start) + "," + UbicacionRecordVariable ;
                    regs.add(reg);
                    int RecordsTotales = lector.getRecordsTotales(lector.getRaiz());
                    int recordaux = RecordsTotales;
                    while(true){
                        try{
                            System.out.println(lineas[UbicacionRecordVariable+RecordsTotales-1]);
                            salida = lineas[UbicacionRecordVariable+RecordsTotales-1].substring(start-1, start-1+len);

                            Nreg += 1;
                            reg = Nreg + "," + salida + "," + (start) + "," + (UbicacionRecordVariable+RecordsTotales) ;
                            regs.add(reg);

                        }catch(Exception e){ break; }
                        RecordsTotales = RecordsTotales + recordaux; 
                    }
                }catch(Exception e){}
 */